backend:
  name: git-gateway
  branch: main
media_folder: "src/img"
public_folder: "/img"
collections:
    - name: "page"
      label: "Page"
      folder: "src/pages"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", modes: ["raw"] }